---
openapi: 3.0.3
info:
  title: Booking API
  description: This is the API of the User service
  contact:
    email: gabriel.aillet@imt-atlantique.net
  license:
    name: GPL v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 1.0.0
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
paths:
  /:
    get:
      tags:
      - developers
      summary: home page of the service
      description: |
        Nothing to do
      operationId: home
      responses:
        "200":
          description: welcome message
          content:
            text/html:
              schema:
                type: string
                example: <h1>Test</h1>
  /users/{user_Id}:
    get:
      tags:
        - developers
      summary: get user info that have user_Id
      description: |
        get user info that have user_Id
      operationId: getUserInfoById
      responses:
        "200":
          description: get user info that have user_Id
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/userItem'
        "400":
            description: bad input parameter


  /users/{timeSinceLastActivity}:
    get:
        tags:
          - developers
        summary: get list of users
        operationId: getUserSinceTime
        responses:
          "200":
            description: get users that did not use the platform since timeSinceLastActivity or more
            content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/users'

components:
  schemas:
    users:
      required:
        - userItem
      type: array
      items:
        $ref: '#/components/schemas/userItem'
    userItem:
      required:
      - id
      - name
      - last_active
      type: object
      properties:
        id:
          type: string
          example: chris_rivers
        name:
          type: string
          example: Chris Rivers
        last_active:
          type: integer
          example: 1360031010